add_newline = true
follow_symlinks = false
continuation_prompt = '[▶▶ ](#51576d)'

format = """
[](#8caaee)\
$c\
$cmake\
$cobol\
$daml\
$dart\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$gleam\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$quarto\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$typst\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$directory[](#8caaee)\
\
( [](#51576d)$git_branch[](fg:#414559 bg:#51576d)\
($git_status)[](#414559)) 
"""

right_format = "$character(  $cmd_duration)"

[cmd_duration]
format = '[$duration](#8caaee)'

[character]
success_symbol = ''
error_symbol = '[](bold #e78284)'
vimcmd_symbol = '[](bold #ef9f76)'

[git_branch]
format = "[ $branch ]($style)"
style = "bg:#51576d fg:#8caaee"
[git_status]
format = "[$all_status]($style)"
style = "bg:#414559 fg:#8caaee"

[directory]
style = "bg:#8caaee fg:#232634"
format = "[$path]($style)"
truncation_length = 1

[directory.substitutions]
"0" = " external"
"Andriod" = " andriod"
"Downloads" = " downloads"
".config" = " config"
"~" = " home"

[bun]
style = "bg:#8caaee fg:#232634"
format = "[$symbol]($style)"

[buf]
style = "bg:#8caaee fg:#232634"
format = "[$symbol]($style)"

[cmake]
style = "bg:#8caaee fg:#232634"
format = "[$symbol]($style)"

[cobol]
style = "bg:#8caaee fg:#232634"
format = "[$symbol]($style)"

[crystal]
style = "bg:#8caaee fg:#232634"
format = "[$symbol]($style)"

[daml]
style = "bg:#8caaee fg:#232634"
format = "[$symbol]($style)"

[dart]
style = "bg:#8caaee fg:#232634"
format = "[$symbol]($style)"

[deno]
style = "bg:#8caaee fg:#232634"
format = "[$symbol]($style)"

[dotnet]
style = "bg:#8caaee fg:#232634"
format = "[$symbol]($style)"

[elixir]
style = "bg:#8caaee fg:#232634"
format = '[$symbol]($style)'

[elm]
style = "bg:#8caaee fg:#232634"
format = '[$symbol]($style)'

[erlang]
style = "bg:#8caaee fg:#232634"
format = '[$symbol]($style)'

[fennel]
style = "bg:#8caaee fg:#232634"
format = '[$symbol]($style)'

[gleam]
style = "bg:#8caaee fg:#232634"
format = '[$symbol]($style)'

[golang]
style = "bg:#8caaee fg:#232634"
format = '[$symbol]($style)'

[gradle]
style = "bg:#8caaee fg:#232634"
format = '[$symbol]($style)'

[haxe]
style = "bg:#8caaee fg:#232634"
format = '[$symbol]($style)'

[helm]
style = "bg:#8caaee fg:#232634"
format = '[$symbol]($style)'

[java]
style = "bg:#8caaee fg:#232634"
format = '[$symbol]($style)'

[julia]
style = "bg:#8caaee fg:#232634"
format = '[$symbol]($style)'

[kotlin]
style = "bg:#8caaee fg:#232634"
format = '[$symbol]($style)'

[lua]
style = "bg:#8caaee fg:#232634"
format = '[$symbol]($style)'

[meson]
style = "bg:#8caaee fg:#232634"
format = '[$symbol]($style)'

[nim]
style = "bg:#8caaee fg:#232634"
format = '[$symbol]($style)'

[nodejs]
style = "bg:#8caaee fg:#232634"
format = '[$symbol]($style)'

[ocaml]
style = "bg:#8caaee fg:#232634"
format = '[$symbol(\($switch_indicator$switch_name\) )]($style)'

[opa]
style = "bg:#8caaee fg:#232634"
format = '[$symbol]($style)'

[perl]
style = "bg:#8caaee fg:#232634"
format = '[$symbol]($style)'

[php]
style = "bg:#8caaee fg:#232634"
format = '[$symbol]($style)'

[pulumi]
style = "bg:#8caaee fg:#232634"
format = '[$symbol$stack]($style)'

[purescript]
style = "bg:#8caaee fg:#232634"
format = '[$symbol]($style)'

[python]
style = "bg:#8caaee fg:#232634"
format = '[$symbol]($style)'

[quarto]
style = "bg:#8caaee fg:#232634"
format = '[$symbol]($style)'

[raku]
style = "bg:#8caaee fg:#232634"
format = '[$symbol]($style)'

[red]
style = "bg:#8caaee fg:#232634"
format = '[$symbol]($style)'

[rlang]
style = "bg:#8caaee fg:#232634"
format = '[$symbol]($style)'

[ruby]
style = "bg:#8caaee fg:#232634"
format = '[$symbol]($style)'

[rust]
style = "bg:#8caaee fg:#232634"
format = '[$symbol]($style)'

[solidity]
style = "bg:#8caaee fg:#232634"
format = '[$symbol]($style)'

[typst]
style = "bg:#8caaee fg:#232634"
format = '[$symbol]($style)'

[swift]
style = "bg:#8caaee fg:#232634"
format = '[$symbol]($style)'

[vagrant]
style = "bg:#8caaee fg:#232634"
format = '[$symbol]($style)'

[vlang]
style = "bg:#8caaee fg:#232634"
format = '[$symbol]($style)'

[zig]
style = "bg:#8caaee fg:#232634"
format = '[$symbol]($style)'
